### ISSUE TITLE
Single It block with multiple test cases

### ISSUE THREAD

**Issue by pawankondavatysonos** [webdriverio-community/wdio-testrail-reporter#202]
Can I tag a single test script  with multiple test cases Id's?

For e.g. I have 3 test cases which i have combined in my test script into single `it` block like below

```
 it(`C33651313 C33651310 C33651312  Verify Code value`, async function () {
      Command.log(`Running Test :${locale}`)
      // addTestRailComment(`Locale:\t${locale}`)
      if (local === 'gb') {
        expect(true).to.be.equal(false)
      }
    })
  })
```
So can i have the test report the test run results to each of the test case id's C33651313 C33651310 and C33651312 ?
Currently when i try this I see the following

[0-0] 2023-07-26T00:33:32.007Z ERROR TestrailReporter: Failed to update test run: Request failed with status code 400
[0-0] 2023-07-26T00:33:32.598Z ERROR TestrailReporter: Failed to update test run results: Request failed with status code 400

**Comment by therealbrad** [comment]
@pawankondavatysonos No, that is not supported. Tests should have a 1:1 relationship with the cases in TestRail. Mocha is built around the fact that `it` is a single test. You either need to combine those 3 tests into a single TestRail case or split the test into 3 `it` blocks in mocha.
