### ISSUE TITLE
"Some reporters are still unsynced" error message always displayed

### ISSUE THREAD

**Issue by therealbrad** [webdriverio-community/wdio-testrail-reporter#6]
```
[0-3] 2022-12-10T19:29:06.554Z ERROR @wdio/runner: Error: Some reporters are still unsynced: CJSTestrailReporter
[0-3]     at Timeout.<anonymous> (/Users/bderman/git/wdio/node_modules/@wdio/runner/build/reporter.js:87:35)
[0-3]     at listOnTimeout (node:internal/timers:564:17)
[0-3]     at process.processTimers (node:internal/timers:507:7)
```

@christian-bromann 
This error occurs once for each runner at the start of the tests even though everything is functionally working correctly. What's the best way to debug which promises are still not resolved?

**Comment by christian-bromann** [comment]
Check `#requestPromises` here: https://github.com/webdriverio-community/wdio-testrail-reporter/blob/main/src/reporter.ts#L60

**Comment by therealbrad** [comment]
I forced synced to true with no adverse affects. I'll leave this open for a bit in case someone complains about that change breaking something but I don't think it will because we don't need to wait for a response from TestRail to know the results were sent.

**Comment by therealbrad** [comment]
@jyoti-075 Can I get your configs to try to reproduce it?

**Comment by jyoti-075** [comment]
Hi @therealbrad  : Below is my config: 

`reporters:
        [
            ['testrail',
                {
                    projectId: 10,
                    suiteId: 112,
                    domain: 'xxx.testrail.io',
                    username: process.env.TESTRAIL_USERNAME,
                    apiToken: process.env.TESTRAIL_API_TOKEN,
                    runName: 'BOL_Framework_Run_' + process.platform + '_Created_On_' + Date().toString().slice(4, 25) + 'IST',
                    oneReport: true,
                    includeAll: false
                }
            ]
        ],`
Below are the dev dependencies from package.json 

`{
  "name": "bol-automation",
  "version": "1.0.0",
  "description": "WebdriverIO(Mocha) Framework for BOL automation",
  "main": "index.js",
  "scripts": {
    "test": "wdio run wdio.conf.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@wdio/cli": "^8.3.5",
    "@wdio/local-runner": "^8.3.5",
    "@wdio/mocha-framework": "^8.3.0",
    "@wdio/testrail-reporter": "^0.1.9",
    "chai-webdriverio": "^1.0.0",
    "chromedriver": "^102.0.0",
    "wdio-chromedriver-service": "^8.0.1",
    "webdriverio": "^8.3.5"
  }
}
`
Please let me know if anything else will be needed , even with 0.1.9 version , there was 1 instance where i was able to get the results to testrail , that happened if i add the reportersyncinterval in my config

reporterSyncInterval: 10 * 1000,

Once i add this results were pushed, but without this interval ,nothing happens , not sure if its something wrong in my config.
If it works for you, I'll leave it upto you to decide if it was just something wrong in my system, as i have now reverted to the older version with sync interval to avoid the timeout error.

**Comment by therealbrad** [comment]
@jyoti-075 Adding `reporterSyncTimeout` was going to be my suggestion. If the call to TestRail takes more than 5 seconds then the reporter will time out before the call finishes. TestRail has been notably slower since their latest update so I think this is the solution.

**Comment by therealbrad** [comment]
@mikesalvia Good timing! I was literally just looking at this again. I'll review the PR.

**Comment by mikesalvia** [comment]
@therealbrad Awesome! Glad I can be of help!

**Comment by shivaprakashwsv** [comment]
@christian-bromann, could you please advise how to pass proxy information in reporter options? I am facing "ERROR TestrailReporter: Failed to get last test run: Request failed with status code 407" error

**Comment by christian-bromann** [comment]
> should I upgrade wdio to ver8?

Yes, I always recommend that.
