### ISSUE TITLE
Not able to push test results to TestRail

### ISSUE THREAD

**Issue by jyoti-075** [webdriverio-community/wdio-testrail-reporter#71]
Hi Team,

I am using Webdriver IO with mocha framework. I would like my test results to be pushed to testrail, but its failing 
The use case passes but at the reporter it gives the below error:

![image](https://user-images.githubusercontent.com/102945869/219871601-a0ea313d-33bd-4bb3-b525-1122753682e5.png)

![image](https://user-images.githubusercontent.com/102945869/219871613-355c3a06-0245-4ce0-b2ef-0209be00e94b.png)

Below is the configuration provided in reporters in wdio config file:
reporters:
        [
            ['testrail', {
                projectId: 7,
                suiteId: 24,
                domain: 'xxxx.testrail.io',
                username: process.env.TESTRAIL_USERNAME,
                apiToken: process.env.TESTRAIL_API_TOKEN,
                runName: 'test',
                oneReport: true,
                includeAll: false
            }
            ]
            
API is enabled on the test rail end , also have tried with password also, getting the same error 

For the test case, have provided the same title as that from Testrail, describe block have given the suite name and it block have given use case name to match with testrail

Can you please help me figure out what is wrong here, also is there a way i can see the API calls to testrail and their response for further debugging.

**Comment by therealbrad** [comment]
> domain: 'xxxx.testrail.io',

You have to replace this with your testrail instance. If you're using their cloud version, it's usually `yourcompany.testrail.io`.

**Comment by jyoti-075** [comment]
Thanks Brad, i had replaced it with my companies domain, had just hidden it here for privacy reasons. 

The errors are seen with the correct domain, is there anything else i have missed for configuration ?

**Comment by therealbrad** [comment]
401 is an auth error so either the domain, username or api key is incorrect. Can you connect to the API with those credentials with anything else like a curl request?

**Comment by christian-bromann** [comment]
Should we check for an error message in the response and populate it in the message?

**Comment by jyoti-075** [comment]
I have regenerated the key Brad, and now I am getting a 400 which is a bad request, is it possible to check the exact URL that's going in the API request to see what is wrong? Even for me to test it manually I am not clear on how to form the URL as we don't pass the test case id in the configuration. If I can get the exact URL that's being called in the API request, I can try it manually first with my credentials.

**Comment by jyoti-075** [comment]
This is what I have tried. A get request to TestRail API 

![image](https://user-images.githubusercontent.com/102945869/219880965-df413941-a47e-4a40-b133-5d4d02acf946.png)

I have provided the username with user@company.com but in error message if you see, it has taken jyoti@company_com (underscore instead of dot), probably that's causing the 400.

Could you please recheck if i have provided something incorrect?

**Comment by therealbrad** [comment]
This is the request that is failing:
https://github.com/webdriverio-community/wdio-testrail-reporter/blob/main/src/api.ts#L106

`https://yourcompany.testrail.io/index.php?/api/v2/get_runs/7&is_completed=0&created_after=${unixTimeStamp}&suite_id=24`

Response codes are:
200	Success (the test run is returned as part of the response)
400	Invalid or unknown project
403	No access to the project
429	TestRail Cloud only—Too many requests (see [API rate limit](https://www.gurock.com/testrail/docs/api/getting-started/introduction#APIRateLimit))

**Comment by therealbrad** [comment]
> Should we check for an error message in the response and populate it in the message?

@christian-bromann Yeah, that's probably a good idea. I'm going to add some code soon to set options by name rather than ID which should help reduce confusion, too. I have it working in[ the service](https://github.com/therealbrad/wdio-testrail-service) that's been occupying my free time but i'll use the code here, too. I'll add error responses when I add that.

**Comment by jyoti-075** [comment]
Thanks @therealbrad , i was able to get the API response 200 manually first post which i tried again 

This time the test run did get created :) but the update on test run is failing 

[0-0] 2023-02-19T07:40:45.967Z INFO TestrailReporter: Create new run 'automation_run_3' with id: 112

[0-0] 2023-02-19T07:40:48.634Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-02-19T07:40:48.726Z ERROR TestrailReporter: Failed to update test run: Request failed with status code 400
[0-0] 2023-02-19T07:40:48.734Z INFO @wdio/runner: Wait for 1 reporter to synchronise

From code i could see that this is what is getting called for the update test run 

`${this.#baseUrl}/add_results_for_cases/${runId}`, 

But was curios on where I need to provide the runId ? This is how my test case looks 

![image](https://user-images.githubusercontent.com/102945869/219935616-58730c4e-08d3-4c83-8872-57bbaede989c.png)

This test case title isn't present in TestRail yet , my understanding is it will add this use case title to the run created? 

Please correct me if i am wrong somewhere.

**Comment by therealbrad** [comment]
The runID is generated automatically so no need to provide it. Also, your suite name does not need to appear anywhere - it always uses the Suite ID provided in the config.

The reporter will not create new test cases - only report on existing test cases. Once your test case is in TestRail, prepend the test case ID to your mocha test description. e.g. ```it("C12345 Page loads correctly", async () => {
```

**Comment by jyoti-075** [comment]
Thanks @therealbrad, appending the ID worked, is it possible to create multiple suites under the same test run? 
I would like to have multiple suites under the same run and then have separate use cases under each run, is there a format for conf file for multiple suites? 

Also, even though my use case passed, I am getting the timeout error in the end:

[0-0] 2023-02-19T14:20:18.520Z INFO @wdio/runner: Wait for 1 reporter to synchronise
[0-0] 2023-02-19T14:20:18.621Z ERROR @wdio/runner: Error: Some reporters are still unsynced: TestRailReporter
[0-0]     at Timeout.<anonymous> (file:///C:/jyoti.sista/workspace/code-repos/automation/node_modules/@wdio/runner/build/reporter.js:111:35)
[0-0]     at listOnTimeout (node:internal/timers:564:17)
[0-0]     at process.processTimers (node:internal/timers:507:7)

**Comment by therealbrad** [comment]
Glad you for it working!

TestRail does not support creating a test run with test cases that are in different Suites. (Notice when you click the Add Test Run button, you are immediately prompted to select a single test suite.)

TestRail does support creating a Test Plan which can contain multiple test runs. Each of those test runs can be of different suites, but this reporter does not hanle test plans. That would be a feature request. I looked into it and it would require quite a lot of work to incorporate.

The error "Some reports are still unsynced", is https://github.com/webdriverio-community/wdio-testrail-reporter/issues/6 and I have't found a good solution for it yet. 

Since you got this working, I'm marking the issue resolved.

**Comment by jyoti-075** [comment]
Sure, Thanks @therealbrad for your support.
